### PR TITLE
finished setting up a basic layout for testers in BDD style

### PR DESCRIPTION
**Pull request by hoangdangninh**
first time in GO ~ I probably violate quite a bit of good practices out there, sorry all

### CODE REVIEW

**Comment by hoangdangninh** [comment]
Oh no, why does it fail? : (

**Comment by hoangdangninh** [comment]
Ah, I think I figured out the recent why this failed. This is a bit like integration/system testing so it needs some context. 
Can I simulate something like `localhost:2082/index.html` inside my test? @jcbwlkr  

image

**Comment by jcbwlkr** [comment]
I would probably do something like this https://github.com/ardanlabs/gotraining/blob/master/topics/web/testing/example3/unit_test.go

**Comment by george-e-shaw-iv** [comment]
@hoangdangninh I agree with Jacob's idea of implementation. I don't think we should import another go package for this type of testing, however it is a good idea to set up these tests. You can create a separate route just for testing if you want to, or use preexisting ones in a unique way that isn't likely to change. Its up to you.

**Comment by hoangdangninh** [comment]
So, I followed our convention and wrote the first test for the webhost, but ran into this issue. It seems like httptest did not serve from the directory we expected.
Could someone take a look?

```
package webhost

import (
	"testing"
	"log"
	"net/http/httptest"
	"net/http"
	. "github.com/smartystreets/goconvey/convey"
)

func TestWebhost(t *testing.T) {
	Convey("Given a HTTP request for /index.html on client side", t, func() {

		web := NewPrivateHost()

		log.Print("Listening (private) on localhost:2082, serving out of the document_roots/webhost/ directory...")
		server := httptest.NewServer(&web)
		defer server.Close()

		res, err := http.Get(server.URL)
		if err != nil {
			log.Fatal(err)
		}
		Convey("Then the response status code should be 200", func() {
			So(res.StatusCode, ShouldEqual, 200)
		})
	})
}
```

image

**Comment by jcbwlkr** [comment]
You are correct. The path listed in the `NewWebHost` function is relative to the current working directory. Tests are always ran in the directory of the package under test.

You could change `NewWebHost` to accept a path to the document root?

**Pull request closed without merging**
